// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture
RWStructuredBuffer<float3> dataBuffer;
float time;
float speed;
float scale;
float size;


[numthreads(1024,1,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
	dataBuffer[id.x] = float3(0,sin(time*speed + dataBuffer[id.x].x + dataBuffer[id.x].y + dataBuffer[id.x].z)*scale, 0);
}
